### PR TITLE
Update slack and irc dependencies

### LINKED ISSUE #31: openssl package conflict
error: native library `openssl` is being linked to by more than one version of the same pac
kage, but it can only be linked once; try updating or pinning your dependencies to ensure t
hat this package only shows up once

  openssl-sys v0.6.7
  openssl-sys v0.9.10

### PR DESCRIPTION
**Pull request by smackysnacks**
This PR updates the `irc` crate to version 0.12 and the `slack` crate to version 0.18. It then changes the irc and slack adapter code to work with these new versions.

This also happens to fix #31 and the travis build.

### CODE REVIEW

**Comment by smackysnacks** [comment]
There is an issue with the latest version of the slack crate that causes outbound messages to be queued until a new message is received.

https://github.com/slack-rs/slack-rs/issues/88

**Comment by jwilm** [comment]
Oh wow, thanks!

I've been meaning to do this myself; really excited you decided to make a PR 😁 

Regarding the outbound message issue, I think it was recommend to send messages via the HTTP API instead of using the WebSocket API. Any thoughts on that?

**Comment by smackysnacks** [comment]
Thanks for creating this project :). I'm also a big fan of alacritty.

After skimming https://api.slack.com/faq#events_api it looks like we definitely want to use the Real Time Messaging API (websockets) for receiving. On the other hand, using the Web API to send messages reliably as a workaround to that slack-rs issue is a possibility. I'd still prefer to see that issue resolved though.

**Comment by jwilm** [comment]
@rmbreak I don't disagree, but it sounds like the HTTP is far more capable with formatting, and it might be a better default for the chatbot. The RT api only supports the same formatting as regular users.

**Comment by jwilm** [comment]
>  I'm also a big fan of alacritty.

:grin: thanks!

**Comment by smackysnacks** [comment]
I wasn't aware of advanced formatting like attachments. In that case using the Web API for sending looks like the right way to go. The slack-rs team also has a web API crate.

@jwilm I'd like to get this PR through so the doc links can be updated and the brain trait started. A big downside of merging this PR now is obviously messages not sending within a reasonable amount of time. It's your call, let me know how I can help.

**Comment by smackysnacks** [comment]
@jwilm I'm still very much interested in contributing to the project. Let me know how I can direct my efforts.

**Comment by jwilm** [comment]
Sorry for the delay here. Let's merge this as-is. I'm going to hold off on publishing a new version until we can fix the message sending problem on slack. Seems that using the HTTP API is the right way to go. How would you feel about working on that next?

**Comment by jwilm** [comment]
Thanks for your contribution and interest in the project btw. I don't have as much time as I would like to work on this anymore, but it's still something I'm very interested in.

Feel free to message me on either moz or freenode irc if you want more immediate feedback. Sometimes GitHub issues aren't the best because once a notification is gone, it's gone.

**Pull request merged**
